spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dental_lab_app?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: springboot_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false

# Enable debug logging for development profile
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE # show query bind parameter values
    root: INFO
    com.dentallab: INFO
    com.dentallab.api.controller.WorkController: DEBUG
    com.dentallab.api.controller.WorkOrderController: DEBUG
jwt:
  log-tokens: true